name: Deploy Vue App to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v2
        with:
          ref: deploy

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm install

      - name: Build Vue app
        run: npm run build
        env:
          VUE_APP_PUBLIC_PATH: ${{ vars.VUE_APP_PUBLIC_PATH }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist
          clean: true
  
      - name: Create 404.html
        run: cp dist/index.html dist/404.html