name: Deploy Vue App to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Vue app
        run: npm run build

      - name: Setup Pages branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b newdist
          git add --force dist
          git commit -m "new dist"
          git push -u origin newdist
          git push origin `git subtree split --prefix dist newdist`:gh-pages --force
          git push origin --delete newdist
